### ISSUE TITLE
Add Player is AFK & slash commands?

### ISSUE THREAD

**Issue by Thundros** [nickyvanurk/3d-multiplayer-browser-shooter#2]
Hi @nickyvanurk ! First off, I just want to start by saying, "THIS IS A WORK OF ART! PLEASE CONTINUE WORKING ON IT & DON'T LET ANYTHING STOP YOU!" :) Secondly, I just thought I'd request 2 small features. The ability for when a player hasn't tapped a key or moved the mouse within x amount of minutes, that the Server sends a message to the Client saying "that player is AFK or Away", and it also makes the Player's name tag as well as in the chat window say : 

< My Name Here >
        < Away >

Finally, can you please add a few commands to the Server allowing for chat system commands?

Once again, thank you VERY much for the AWESOME project! Please continue it!

**Comment by Thundros** [comment]
Hello @nickyvanurk ?

**Comment by nickyvanurk** [comment]
Hi there! Thanks for the kind words. What chat commands are you thinking about? I don't see any use for them.

**Comment by Thundros** [comment]
Just a general type of slash command, X, Y, Z, Pitch, Yaw, Roll FROM THE SERVER would be good so I can continue working on the project & adding to it! :)

**Comment by nickyvanurk** [comment]
I don't see the point of adding it. What benefit would it provide for the user (besides you)?

**Comment by Thundros** [comment]
@nickyvanurk Well, for the user, I believe actually /away would be appropriate to allow the player to tell other players they are away from keyboard. I was actually gonna use the coordinates to beta test it.

**Comment by nickyvanurk** [comment]
When I continue the project I will consider it. Thanks for the suggestion.
