### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Browhatthe** [nickyvanurk/3d-multiplayer-browser-shooter#29]
Is it possible you can update the herokuapp website to be the same as the version on your personal website?

**Comment by Browhatthe** [comment]
Can you update the controls for https://urk-void.herokuapp.com/ to be wasd and space to fire?

**Comment by nickyvanurk** [comment]
@Browhatthe The herokuapp is a newer (unfinished) version that included multiplayer. The one on my personal website doesn't include any multiplayer. However if you want the code for the one on my personal website you can just browse the git commit history. This project has had many versions.
