### ISSUE TITLE
Hole punching?

### ISSUE THREAD

**Issue by Thundros** [nickyvanurk/3d-multiplayer-browser-shooter#4]
Hi @nickyvanurk ! First off, I'd just like to say: AWESOME job on this demo! PLEASE give yourself a pat on the back! Keep up the GREAT work! <3

Second, I'd like to ask if you could add hole punching without any external service such as google in node so we can allow friends to come check out this demo & watch it grow?

Once again, THANK YOU for the amazing work you do & have an EXCELLENT memorial day! <3

**Comment by nickyvanurk** [comment]
Hey @Thundros thank you for the kind words once again :)) You can follow my progress on my website: https://nickyvanurk.com/void/ Currently there is no networking yet tho, focusing on a good core engine. You can also reach me on Discord: Mr. Sockpuppet#9355

**Comment by Thundros** [comment]
Hello @nickyvanurk ! You are welcome! <3 Once there is networking, can you do this without any services such as google, etc? I KNOW node.js can punch holes through both UDP & TCP & I wanna be able to allow my friends to try out your demo / game on-demand without having my router blocking ports.

**Comment by nickyvanurk** [comment]
You can use Ngrok fot that, it's a free program I use.
